version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - run:
          name: Install OS dependencies
          command: |
            apt-get update
            apt-get install -y git build-essential libpcre3-dev zlib1g-dev libcurl4-openssl-dev wget curl tar cmake clang-format
      - run:
          name: Run clang-format
          command: |
            changes=$(find ./ -iname *.h -o -iname *.cpp | xargs clang-format -output-replacements-xml | grep -c "<replacement " || true)
            if [ $changes != 0 ]
            then
              echo "Did not pass clang-format, consider running: find ./ -iname *.h -o -iname *.cpp | xargs clang-format -i"
              exit 1
            fi
      - run:
          name: Compile OpenTracing dependency
          command: |
            wget -O opentracing-cpp.tar.gz https://github.com/opentracing/opentracing-cpp/archive/v1.3.0.tar.gz
            tar zxvf opentracing-cpp.tar.gz
            mkdir opentracing-cpp-1.3.0/.build
            pushd opentracing-cpp-1.3.0/.build
            cmake ..
            make
            make install
            popd
      - run:
          name: Run Datadog C++ OpenTracing tests
          command: |
            rm -rf .build
            mkdir .build
            pushd .build
            cmake ..
            make
            ctest --output-on-failure
            popd
